### ISSUE TITLE
MEM transition

### ISSUE THREAD

**Issue by ktoddbrown** [tilbud/rCTM#10]
What needs to happen to extend rCTM to rMEM? How are the two models different?

**Comment by HolmquistJ** [comment]
Finally have some time for this. Maybe will take me more than an hour, but I'm not as quick as you. I think I'll build in an Rmd doc to show some various components and optionalities I want to build in. Should I build in a new repo, and make full blown MEM use this package as a requirement, or should I build in this one? If the first we should still host in Tillibud I think.

**Comment by HolmquistJ** [comment]
@ktoddbrown could we code optionality in CTM where we directly enter in sediment delivered to the surface (g/m2), skipping over the step where you calculate it as a function of n tides, and flooding depth? I think that's my cleanest line to pull it into full-blown MEM since the sediment delivery is dynamic, and I want to work in some optionalities where we're not constrained by the assumption of 0 flooding above MHW and 704 tides a year.

Worked on it today. It's about half done!

**Comment by ktoddbrown** [comment]
You can just write a second mineral input function that accepts a time, marsh depth, and tide height. Similarly I would suggest breaking out the root inputs into a function and making that depend on marsh depth and tide height. Let me know if you want me to code this up! Shouldn't take too long :D 

I'm going to suggest that we try to keep everything in one package just for ease of maintaince if nothing else.

**Comment by HolmquistJ** [comment]
We have an initial version that runs in less than a second, so I'm going to close this and open up a new issue on performance improvements.
