### ISSUE TITLE
Track OM exiting cohorts

### ISSUE THREAD

**Issue by HolmquistJ** [tilbud/rCTM#19]
In addCohort could we add a cohort tracking the annual organic matter exiting the other organic matter pools?

**Comment by tilbud** [comment]
Sure.  If I understand your question.  Actually mem calculates respiration by cohort.  That is the same thing yes?Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: James Holmquist <notifications@github.com> Date: 10/28/19  7:58 PM  (GMT-05:00) To: tilbud/rCTM <rCTM@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [tilbud/rCTM] Track OM exiting cohorts (#19) 
In addCohort could we add a cohort tracking the annual organic matter exiting the organic matter pools?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tilbud/rCTM/issues/19?email_source=notifications\u0026email_token=ACAWM2ZPLZORT3YZFJ6SPZDQQ54DTA5CNFSM4JGBSSKKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HU5GYWA",
"url": "https://github.com/tilbud/rCTM/issues/19?email_source=notifications\u0026email_token=ACAWM2ZPLZORT3YZFJ6SPZDQQ54DTA5CNFSM4JGBSSKKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HU5GYWA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by HolmquistJ** [comment]
We did this.
